language: php
php: 5.6

services: mongodb

env:
  - MONGO_VERSION=1.5.8 PREFER_LOWEST=""

before_script:
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
    - echo session.gc_probability = 0 >> $INI_FILE
    - yes '' | pecl -q install -f mongo-${MONGO_VERSION}
    - php --ri mongo
    - composer self-update
    - composer install

script:
    - sh run_tests.sh
