language: php
php: 5.6

env:
  - MONGO_VERSION=1.5.8 PREFER_LOWEST=""

before_script:
    - yes '' | pecl -q install -f mongo-${MONGO_VERSION}
    - php --ri mongo
    - composer self-update
    - composer install

script:
    - sh run_tests.sh
