api_admin_user_add:
    path: /api/admin/user
    defaults: { _controller: AppBundle:Api/AdminUser:add }
    methods: [PUT]

api_admin_user_update:
    path: /api/admin/user/{username}
    defaults: { _controller: AppBundle:Api/AdminUser:update }
    methods: [POST]
    requirements:
        username: \w+

api_admin_user:
    path: /api/admin/user/{username}
    defaults: { _controller: AppBundle:Api/AdminUser:get }
    methods: [GET]
    requirements:
        username: \w+

fos_user_security_login:
    path: /api/login
    defaults: { _controller: AppBundle:Api/Security:login }
    methods: [POST]

fos_user_security_logout:
    path:  /api/logout
    defaults: { _controller: AppBundle:Api/Security:logout }