api_auth:
    path: /api/auth
    defaults: { _controller: AppBundle:Api/AdminAuth:main }
    requirements:
        _method: POST

api_admin_user_add:
    path: /api/admin/user
    defaults: { _controller: AppBundle:Api/AdminUser:add }
    methods: [PUT]

api_admin_user_update:
    path: /api/admin/user/{username}
    defaults: { _controller: AppBundle:Api/AdminUser:update }
    methods: [POST]
    requirements:
        username: \w+

api_admin_user:
    path: /api/admin/user/{username}
    defaults: { _controller: AppBundle:Api/AdminUser:get }
    methods: [GET]
    requirements:
        username: \w+