services:
    fos_user.doctrine_registry:
        alias: doctrine_mongodb

    em.exception.listener:
        class: AppBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }