AppBundle\Document\User:
    properties:
        username:
            - NotBlank: { message: 'This field is required' }
            - Length:
                min: 3
                minMessage: 'This field must be at least {{ limit }} characters long'